apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: hello
  namespace: default
spec:
  steps:
    - name: say-hello
      image: alpine
      script: |
        echo "Hello depuis Tekton !"
        echo "Tekton fonctionne dans mon cluster"