apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-vibes
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-vibes
  template:
    metadata:
      labels:
        app: weather-vibes
    ## Apres audit avec polaris - il faut ajouter la section securityContext pour securiser le container
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
    spec:
      containers:
      - name: weather-vibes
        image: adriendockeraccount/weather-vibes:b7686ece73b848d7b57fa1e63f0ab6cda4eba419
        ports:
        - containerPort: 8000
        env:
        - name: OPENWEATHER_API_KEY
          valueFrom:                        # ← NOUVEAU : la clé vient d'un Secret !
            secretKeyRef:
              name: weather-secret          # le nom du Secret
              key: openweather-api-key              # la clé dans le Secret
        ## Apres audit avec polaris - il faut ajouter la section securityContext pour securiser le container
        securityContext:
          allowPrivilegeEscalation: false