apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: weather-secret
  namespace: default
spec:
  encryptedData:
    openweather-api-key: AgBztvu3juW4KcXEe3nES3/7UV4Z1F5z/xlObE1Vzr+9KAfXzEr2ydzljDd25nhg3rFRo4luMV4EABBsJG9Awk1M17UINkFdHI/8zv+qtFEEs+y6qJV6JHn7FWULXE0b3mjWS7nG1KcztQ1yaOCxQ5c2EWmKBoSBlTK9cTv18vgFtkPZauflSuQ88WrLttLu/gxKtltcWHzfchyBcIA6O4R3m8CVL/njsmfGYmTXEuzgKXkgCLEGdBXenExv60t1VP5buu/cguWC+73ONKB/unmYG5YoMu78pf4OBT5bCPVRKGx6JP1tPtgcE707BG4XEhLRPwiwGqhaBVc0npft6To/b3LkXCcQnwupZNIiZwHaVI0HbjQXzM8mVoSO3SqTRkDQjHJYUWQopkrfx2nGoL1q+AbxgeQIgXpr5aQ8TeF5fW2c8mZx2vcODmqt8UDiAiWNEF1gfhhWC9YAaaBQ8CFiUCCooaW5yZf18xJfC8Fb1b9AIIXokiFLXF/8Up7b2Qb44LeeXYNqPPrqvKi/hJwA5/XBgxaMjMjQxqmPS0Rp3jkTGM8HhmluuHaaZRpbukgbJB2B/zq7BSvq3epEeE78QDo74JlbSRGu1/Bi6PqKC10Rke6UaYU8K0yXO4jH/e/QBB0CUY8je9a+0LYsGp/ujqkFIm2oHTVb6BjqOYMlJlFw+y9AkisqSyqhJi6yCjEb9n940F2tVhKyL4HH3jL8eS+iVLo1B1izXo0WTxJSaA==
  template:
    metadata:
      name: weather-secret
      namespace: default