apiVersion: v1
kind: Service
metadata:
  name: weather-vibes
  namespace: default
spec:
  type: NodePort
  selector:
    app: weather-vibes          # cible tes Pods (le label du Deployment)
  ports:
    - port: 80
      targetPort: 8000           # le port de ton appli (8000 !)
      nodePort: 30090            # ton choix (30000-32767)